const express=require('express');
const {isAuthenticatedUser,authorizeRoles}=require('../middleware/auth');
const {getAllProducts,createProduct,updateProduct,deleteProduct,GetProductDetails}=require('../controller/productController');
const router=express.Router();
router.get('/products',getAllProducts);
router.post('/product/new',isAuthenticatedUser,authorizeRoles("admin"),createProduct);
router.put('/product/:id',isAuthenticatedUser,authorizeRoles("admin"),updateProduct);
router.delete('/product/:id',isAuthenticatedUser,authorizeRoles("admin"),deleteProduct);
router.get('/product/:id',GetProductDetails);
module.exports=router;