const express=require('express');
const app=express();
const errorMiddleware=require('./middleware/error');
const cookieParser = require("cookie-parser");
app.use(express.json());
app.use(cookieParser());
app.use('/api/v1',require('./routes/productRoute'));
app.use('/api/v1',require('./routes/userRoute'));
app.use(errorMiddleware);
module.exports=app;